# Cloud Build configuration for Green PM Frontend
steps:
  # Install dependencies and build
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
    env:
      - 'REACT_APP_API_URL=https://${_SERVICE_NAME}-backend-${_REGION}-${PROJECT_ID}.a.run.app'
      - 'REACT_APP_ENVIRONMENT=${_ENVIRONMENT}'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
      '.'
    ]
    dir: 'frontend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--concurrency', '80',
      '--max-instances', '10',
      '--min-instances', '0',
      '--port', '3000',
      '--set-env-vars', 'ENVIRONMENT=${_ENVIRONMENT}'
    ]

# Substitutions
substitutions:
  _ENVIRONMENT: 'dev'
  _SERVICE_NAME: 'greenpm-dev-frontend'
  _REGION: 'us-central1'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'